package app.carlosribeiro.homemarket.presentation.theme

import androidx.compose.ui.graphics.Color

// The full Material 3 scheme generated from the brand green #2E7D52 (iOS `Brand.primary`) with the
// Material color utilities (tonal spot, 2021 spec). The light primary is the brand green itself, so the
// app matches iOS. Every role is set, so no component falls back to the baseline purple.
//
// The surfaces follow the iOS design system instead of the generated green tints: the page is the iOS
// `Brand.surface` (#F8FAF9), sheets and dialogs are white and outlines are the iOS gray 5. The navigation
// bar and its indicator use the light green-gray tones of the Stitch prototype.

val BrandGreen = Color(0xFF2E7D52)

val LightPrimary = Color(0xFF2E7D52)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFAFF2C4)
val LightOnPrimaryContainer = Color(0xFF0C5130)
val LightInversePrimary = Color(0xFF93D5A9)
val LightSecondary = Color(0xFF4F6354)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD1E9D5)
val LightOnSecondaryContainer = Color(0xFF0C5130)
val LightTertiary = Color(0xFF3B6470)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBFE9F8)
val LightOnTertiaryContainer = Color(0xFF214C58)
val LightBackground = Color(0xFFF8FAF9)
val LightOnBackground = Color(0xFF181D19)
val LightSurface = Color(0xFFF8FAF9)
val LightOnSurface = Color(0xFF181D19)
val LightSurfaceVariant = Color(0xFFF2F2F7)
val LightOnSurfaceVariant = Color(0xFF6B6F6C)
val LightSurfaceTint = Color(0xFF2E7D52)
val LightInverseSurface = Color(0xFF2C322D)
val LightInverseOnSurface = Color(0xFFEDF2EB)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightOutline = Color(0xFF717971)
val LightOutlineVariant = Color(0xFFE5E5EA)
val LightScrim = Color(0xFF000000)
val LightSurfaceBright = Color(0xFFF8FAF9)
val LightSurfaceContainer = Color(0xFFF2F5F1)
val LightSurfaceContainerHigh = Color(0xFFFFFFFF)
val LightSurfaceContainerHighest = Color(0xFFF2F2F7)
val LightSurfaceContainerLow = Color(0xFFFFFFFF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceDim = Color(0xFFE5E5EA)

val DarkPrimary = Color(0xFF93D5A9)
val DarkOnPrimary = Color(0xFF00391F)
val DarkPrimaryContainer = Color(0xFF0C5130)
val DarkOnPrimaryContainer = Color(0xFFAFF2C4)
val DarkInversePrimary = Color(0xFF2B6A46)
val DarkSecondary = Color(0xFFB5CCBA)
val DarkOnSecondary = Color(0xFF213528)
val DarkSecondaryContainer = Color(0xFF374B3D)
val DarkOnSecondaryContainer = Color(0xFFD1E8D5)
val DarkTertiary = Color(0xFFA3CDDB)
val DarkOnTertiary = Color(0xFF033641)
val DarkTertiaryContainer = Color(0xFF214C58)
val DarkOnTertiaryContainer = Color(0xFFBFE9F8)
val DarkBackground = Color(0xFF101412)
val DarkOnBackground = Color(0xFFDFE4DD)
val DarkSurface = Color(0xFF101412)
val DarkOnSurface = Color(0xFFDFE4DD)
val DarkSurfaceVariant = Color(0xFF414942)
val DarkOnSurfaceVariant = Color(0xFFC0C9C0)
val DarkSurfaceTint = Color(0xFF93D5A9)
val DarkInverseSurface = Color(0xFFDFE4DD)
val DarkInverseOnSurface = Color(0xFF2C322D)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkOutline = Color(0xFF8A938B)
val DarkOutlineVariant = Color(0xFF2E3430)
val DarkScrim = Color(0xFF000000)
val DarkSurfaceBright = Color(0xFF353B36)
val DarkSurfaceContainer = Color(0xFF1A1F1C)
val DarkSurfaceContainerHigh = Color(0xFF222824)
val DarkSurfaceContainerHighest = Color(0xFF2A302C)
val DarkSurfaceContainerLow = Color(0xFF1A1F1C)
val DarkSurfaceContainerLowest = Color(0xFF0A0F0C)
val DarkSurfaceDim = Color(0xFF101412)
